# Generated by Django 3.0.6 on 2020-05-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('lugar_compra', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=120)),
                ('caducidad', models.DateTimeField(verbose_name='Fecha de Caducidad')),
                ('cantidad', models.CharField(max_length=30)),
                ('prioridad', models.IntegerField()),
                ('duracion_promedio', models.IntegerField()),
            ],
        ),
    ]
