# Generated by Django 3.0.6 on 2020-05-18 03:09

import calculavirus.insumos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='marca',
            field=models.CharField(default='image.jpg', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lugarcompra',
            name='img',
            field=models.ImageField(blank=True, default=0, max_length=254, null=True, upload_to=calculavirus.insumos.models.productFile),
        ),
    ]
