# Generated by Django 3.0.6 on 2020-05-21 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_auto_20200518_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='fecha_ultima_compra',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
