# Generated by Django 3.0.6 on 2020-05-23 02:37

import calculavirus.insumos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_auto_20200521_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarcompra',
            name='image',
            field=models.ImageField(blank=True, default='location.png', max_length=254, null=True, upload_to=calculavirus.insumos.models.lugarFile),
        ),
    ]
