# Generated by Django 3.0.6 on 2020-06-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
