# Generated by Django 3.0.6 on 2020-05-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20200509_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinsumo',
            name='comprado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
